### ISSUE TITLE
Add a .gitignore

### ISSUE THREAD

**Issue by hexd0t** [Fthree/SEngine#1]
There are files in your repository that should not be there, Visual Studio .suo/.sdf/.user files for example.
To stop git from adding them, create a .gitignore in your repo root directory that ignores files that don't belong to the source, and untrack the files you've already added. GitHub provides free templates at [https://github.com/github/gitignore](https://github.com/github/gitignore)

**Comment by hexd0t** [comment]
Should have taken a closer look - your .gitignore won't remove files that are already tracked - remove them from git manually.

**Comment by SeanLovesCats** [comment]
Hi addilind, thank you for notifying me! 

I just removed the cached files and the gitignore is now working. I'm busy working on the second issue now!
