### ISSUE TITLE
Provide infos about required dependencies

### ISSUE THREAD

**Issue by hexd0t** [Fthree/SEngine#2]
While bundling the library binaries is convenient for users having exactly the same build setup as you (Windows, Visual Studio version), you have to keep in mind that others will have to retrace your steps of obtaining the library binaries for _their_ environment - a simple list in your ReadMe with links to all the libraries and versions needed to compile your project helps those people out.
[There are other ways of solving this, but none is one-fits-all.](https://programmers.stackexchange.com/questions/110093/how-would-one-handle-external-dependencies-in-an-open-source-project)

**Comment by SeanLovesCats** [comment]
Thank you, I was aware this could become an issue. I'm busy writing a dependency write-up and will make the depends folder unix as well as windows friendly :) 

I will reply once I've sorted the issue out.

**Comment by SeanLovesCats** [comment]
I have added as much information about dependencies as I could. I'll be working on making the engine as IDE/platform agnostic as I can.
